name: pull_request

on:
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: eslint
        uses: actions/checkout@v3
        run: npm run lint:js

      - name: stylelint
        uses: actions/checkout@v3
        run: npm run lint:css

      - name: webpack build
        uses: actions/checkout@v3
        run: npm run build
